services:
  - type: web
    name: quotely-server
    env: node
    plan: free
    buildCommand: npm install && npm install puppeteer
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
